#!/usr/bin/env node
/**
 * Split the mode-prompt spec (prompts/jarvis-mode-prompts-*.md) into
 * prompts/shared.md + prompts/modes/<id>.md, then generate
 * src/core/prompts.gen.ts so the app and the Node test bundle both get the
 * text without a Markdown loader. The .md files are the source of truth;
 * never hand-edit the .gen.ts.
 */
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'prompts');
const spec = readdirSync(dir).filter((f) => /^jarvis-mode-prompts-v[\d.]+\.md$/.test(f)).sort().at(-1);
if (!spec) throw new Error('no prompts/jarvis-mode-prompts-vX.Y.md found');
const md = readFileSync(join(dir, spec), 'utf8');
const version = spec.match(/v([\d.]+)\.md$/)[1];

// Shared contract: the first ```text block after "# Shared contract"
const sharedIdx = md.indexOf('# Shared contract');
const block = (from) => {
  const s = md.indexOf('```text\n', from);
  const e = md.indexOf('\n```', s + 8);
  return md.slice(s + 8, e).trim();
};
const shared = block(sharedIdx);

// Mode prompts: "## <Name> — `<id>`" followed by a ```text block
const modes = {};
const re = /^## .+? — `([a-z]+)`\s*$/gm;
let m;
while ((m = re.exec(md))) modes[m[1]] = block(m.index);

mkdirSync(join(dir, 'modes'), { recursive: true });
writeFileSync(join(dir, 'shared.md'), shared + '\n');
for (const [id, text] of Object.entries(modes)) writeFileSync(join(dir, 'modes', `${id}.md`), text + '\n');

const esc = (s) => JSON.stringify(s);
const out = `// GENERATED by scripts/build-prompts.mjs from prompts/${spec} — do not edit.
// Edit the Markdown in prompts/ and run \`npm run prompts\`.

export const PROMPTS_VERSION = ${esc(version)};

/** The shared contract appended to every mode prompt. */
export const SHARED_CONTRACT = ${esc(shared)};

/** Each mode's own body, keyed by mode id. */
export const MODE_PROMPTS: Record<string, string> = {
${Object.entries(modes).map(([id, t]) => `  ${id}: ${esc(t)},`).join('\n')}
};
`;
writeFileSync(join(root, 'src', 'core', 'prompts.gen.ts'), out);
console.log(`prompts v${version}: shared ${shared.length} chars, modes: ${Object.keys(modes).map((k) => `${k} ${modes[k].length}`).join(', ')}`);
